config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories
    resources :products
    resources :suggestions
    resources :orders
  end
  root "static_pages#home"
  resources :suggestions
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users/registrations"}
  resources :products, only: [:index, :show]
  resources :carts
  resources :products, only: [:index, :show] do
    resources :rates, except: [:destroy]
    resources :comments
  end
  resources :rates, only: [:create, :update]
  resources :comments
  resources :orders
end

app/views/admin/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top navigation2">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t(:title_home), root_path, class: "navbar-brand" %>
    </div>
    <div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to t(:menu_home), "#" %>
          </li>
          <li>
            <%= link_to t(:menu_about), "#" %>
          </li>
          <li>
            <%= link_to t(:menu_product), "#" %>
          </li>
          <li>
            <%= link_to t(:menu_price), "#" %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to t(:menu_edit_profile),
                edit_user_registration_path %>
            </li>
            <li>
              <%= link_to t(:menu_sign_out), destroy_user_session_path,
                method: :delete, data: { confirm: t(:sign_out_sure) } %>
            </li>
          <% else %>
            <li>
              <%= link_to t(:menu_login), new_user_session_path %>
            </li>
            <li>
              <%= link_to t(:menu_sign_up), new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

<nav class="navbar navbar-default navbar-cls-top " role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
      data-target=".sidebar-collapse">
      <span class="sr-only"><%= t "toggle_navigation" %></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t("title_home"), root_url, class: "navbar-brand" %>
  </div>
  <div class="navbar-login">
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to t(:menu_home), "#" %>
          </li>
          <li>
            <%= link_to t(:menu_about), "#" %>
          </li>
          <li>
            <%= link_to t(:menu_product), "#" %>
          </li>
          <li>
            <%= link_to t(:menu_price), "#" %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to t(:menu_edit_profile),
                edit_user_registration_path %>
            </li>
            <li>
              <%= link_to t(:menu_sign_out), destroy_user_session_path,
                method: :delete, data: { confirm: t(:sign_out_sure) } %>
            </li>
          <% else %>
            <li>
              <%= link_to t(:menu_login), new_user_session_path %>
            </li>
            <li>
              <%= link_to t(:menu_sign_up), new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
  </div>
</nav>
<nav class="navbar-default navbar-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="main-menu">
      <li class="text-center">
        <%= image_tag("profile.jpg", class: "user-image img-responsive") %>
      </li>
      <li>
        <%= link_to root_url, class: "active-menu" do %>
          <i class="fa fa-group fa-3x"></i>
          <%= t "menu_users" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_categories_path do %>
          <i class="fa fa-cubes fa-3x"></i>
          <%= t "menu_categories" %>
        <% end %>
      <li>
        <%= link_to admin_products_path do %>
          <i class="fa fa-cutlery fa-3x"></i>
          <%= t "menu_products" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_suggestions_path do %>
          <i class="fa fa-bar-chart-o fa-3x"></i>
          <%= t "menu_suggestions" %>
        <% end %>
      </li>
      <li>
        <%= link_to root_url do %>
          <i class="fa fa-truck fa-3x"></i>
          <%= t "menu_carts" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>