config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories
    resources :products
    resources :suggestions
    resources :orders
  end
  root "static_pages#home"
  resources :suggestions
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users/registrations"}
  resources :products, only: [:index, :show]
  resources :carts
  resources :products, only: [:index, :show] do
    resources :rates, except: [:destroy]
    resources :comments
  end
  resources :rates, only: [:create, :update]
  resources :comments
  resources :orders
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook, :twitter]

  has_many :suggestions
  has_many :orders
  has_many :active_rates, class_name: Rate.name,
    foreign_key: :user_id, dependent: :destroy
  has_many :rating, through: :active_rates, source: :product
  has_many :comments

  enum role: {admin: 0, user: 1}

  has_attached_file :avatar, styles: {mini: Settings.avatar.mini,
    medium: Settings.avatar.medium,
    thumb: Settings.avatar.thumb},
    default_url: Settings.avatar.default_url
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def assign_default_role
    self.add_role :newuser if self.roles.blank?
  end

  def rate product, value
    active_rates.create product_id: product.id, rate: value
    product.update_attributes rating: product.raters.average(:rate)
  end

  def rerate product, value
    active_rates.find_by(product_id: product.id).update_attributes rate: value
    product.update_attributes rating: product.raters.average(:rate)
  end

  def rating? product
    rating.include?product
  end

  def is_user? user
    self == user
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit :name, :tel, :address, :email, :password,
      :password_confirmation, :avatar
  end

  def account_update_params
    params.require(:user).permit :name, :tel, :address, :email, :password,
      :password_confirmation, :current_password, :avatar
  end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != "sessions" %>
  <%= link_to t(:link_login), new_session_path(resource_name) %><br />
<% end -%>
<%- if devise_mapping.registerable? && controller_name != "registrations" %>
  <%= link_to t(:link_signup), new_registration_path(resource_name) %><br />
<% end -%>
<%- if devise_mapping.recoverable? && controller_name != "passwords" &&
  controller_name != "registrations" %>
  <%= link_to t(:link_forgot), new_password_path(resource_name) %><br />
<% end -%>
<%- if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <%= link_to t(:link_did_confirmation),
    new_confirmation_path(resource_name) %><br />
<% end -%>
<%- if devise_mapping.lockable? &&
  resource_class.unlock_strategy_enabled?(:email) &&
  controller_name != "unlocks" %>
  <%= link_to t(:link_did_unlock),
    new_unlock_path(resource_name) %><br />
<% end -%>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}",
      omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>