config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories
    resources :products
    resources :suggestions
    resources :orders
  end
  root "static_pages#home"
  resources :suggestions
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users/registrations"}
  resources :products, only: [:index, :show]
  resources :carts
  resources :products, only: [:index, :show] do
    resources :rates, except: [:destroy]
    resources :comments
  end
  resources :rates, only: [:create, :update]
  resources :comments
  resources :orders
end

app/views/shared/_cart.html.erb
<%= link_to t(:view_all_carts), carts_path %>
<div class="scroll">
  <% @cart.items.each do |item| %>
    <hr>
    <%= image_tag item.product.image.url(:mini) %>
    <%= item.product.name %>
    <table class="table-share-cart">
      <thead>
        <tr>
          <th class="th1"><%= t "cart.quantity" %></th>
          <th class="th2"><%= t "cart.price" %></th>
          <th class="th3"><%= t "cart.action" %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><span><%= item.quantity %></span></td>
          <td><span><%= product_price item.total_price %></span></td>
          <td class="pull-right">
            <%= link_to cart_path(item.product_id),
              method: :delete, remote: true, class: "pull-right" do %>
              <p class="glyphicon glyphicon-trash text-danger
                action-padding"></p>
            <% end %>
            <%= link_to edit_cart_path(item.product_id),
              remote: true, class: "pull-right" do %>
              <p class="glyphicon glyphicon-minus
                text-primary action-padding"></p>
            <% end %>
            <%= link_to cart_path(item.product_id), remote: true,
              method: :put, class: "pull-right" do %>
              <p class="glyphicon glyphicon-plus text-success
                action-padding"></p>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/shared/_cart_online.html.erb
<% @cart.items.each do |item| %>
  <ul>
    <li class="clearfix">
      <%= image_tag item.product.image.url(:mini), class: "productimg" %>
      <h4><%= item.product.name %></h4>
      <div class="clearfix"></div>
      <span class="item-price">
        <%= total_price_product item %>
      </span>
      <span class="quantity">
        <%= t "share_cart_online_quantity" %>
        <%= item.quantity %>
      </span>
    </li>
  </ul>
  <hr>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_error_messages", plural: pluralize(object.errors.count,
        t("error_text")) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_info_right.html.erb
<div class="panel panel-primary text-center no-boder bg-color-green">
  <div class="panel-body">
    <i class="fa fa-bar-chart-o fa-5x"></i>
    <h3><%= t "price_one" %></h3>
  </div>
  <div class="panel-footer back-footer-green">
    <%= t "product_one" %>
  </div>
</div>
<div class="panel panel-primary text-center no-boder bg-color-red">
  <div class="panel-body">
    <i class="fa fa-edit fa-5x"></i>
    <h3><%= t "price_tow" %></h3>
  </div>
  <div class="panel-footer back-footer-red">
    <%= t "product_tow" %>
  </div>
</div>
<div class="panel panel-primary text-center no-boder bg-color-green">
  <div class="panel-body">
    <i class="fa fa-comments-o fa-5x"></i>
    <h4><%= t "price_three" %></h4>
    <h4><%= t "product_three" %></h4>
  </div>
  <div class="panel-footer back-footer-green">
    <i class="fa fa-rocket fa-5x"></i>
    <%= t "product_content" %>
  </div>
</div>