config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories
    resources :products
    resources :suggestions
    resources :orders
  end
  root "static_pages#home"
  resources :suggestions
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users/registrations"}
  resources :products, only: [:index, :show]
  resources :carts
  resources :products, only: [:index, :show] do
    resources :rates, except: [:destroy]
    resources :comments
  end
  resources :rates, only: [:create, :update]
  resources :comments
  resources :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :items
  has_many :comments
  belongs_to :category
  has_many :passive_rates, class_name: Rate.name,
    foreign_key: :product_id, dependent: :destroy
  has_many :raters, through: :passive_rates, source: :user

  enum kind: {food: 0, drink: 1}

  has_attached_file :image, styles: {mini: Settings.image.mini,
    medium: Settings.image.medium,
    thumb: Settings.image.thumb},
    default_url: Settings.image.default_url
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  scope :recent, ->{order created_at: :desc}
  scope :by_category, ->id do
    where category_id: id if id.present?
  end
  scope :is_food, ->{where kind: kinds[:food]}
  scope :is_drink, ->{where kind: kinds[:drink]}
  scope :search_name, ->search do
    where "name LIKE ?", "%#{search}%" if search.present?
  end
  def update_suggestion_status id
    suggestion = Suggestion.find_by id: id
    suggestion.update_attributes status: true
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin_application"
  before_action :load_product, only: [:edit, :destroy, :show]
  before_action :load_categories, only: [:new, :edit, :create]
  load_and_authorize_resource
  before_action :authorize_admin

  def index
    @products = Product.recent.page(params[:page]).per Settings.per_page.products
  end

  def new
    @product = Product.new
    @suggestion = Suggestion.find_by id: params[:object]
  end

  def show
  end

  def edit
  end

  def create
    @product = Product.new product_params
    if @product.save
      if params[:suggestion_id]
        @product.update_suggestion_status params[:suggestion_id]
      end
      flash[:success] = t "flash_success_create_product"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
    if @product.destroy
      flash[:success] = t "flash_success_delete_product"
    else
      flash[:danger] = t "flash_danger_delete_product"
    end
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit :id,
      :category_id, :name, :description, :price, :kind, :image
  end

  def load_product
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:warning] = t "category_isnt_exist"
      redirect_to root_url
    end
  end

  def load_categories
    @categories = Category.all
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Category.all
    params[:filter_by] = :all if params[:filter_by].blank?
    @products = params[:filter_by] == :all ? Product.all :
      Product.send(params[:filter_by])
    @products = @products.search_name(params[:search]).by_category(params[:category_id])
      .page(params[:page]).per Settings.per_page.products
  end

  def show
    @product = Product.find_by id: params[:id]
    @comments = @product.comments.newest.page(params[:page]).per Settings.per_page.comments
    unless @product
      flash[:danger] = t "flash_danger_not_product"
      redirect_to root_path
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def total_price_product cart
    number_to_currency(cart.total_price, unit: t("product_vnd"),
      delimiter: Settings.currency.delimiter,
      format: Settings.currency.format,
      precision: Settings.currency.precision)
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def show_rating string = ""
   rating = "<span class = '#{string}'>☆</span>"
   rating.html_safe
  end
end

app/views/products/_filter_form.html.erb
<%= form_tag products_path, method: :get, class: "form-inline" do %>
  <%= label_tag "#", t("category") %>
  <%= select_tag :category_id,
    options_from_collection_for_select(@categories, :id, :name,
    params[:category_id]),
    {include_blank: t("search_all"), class: "form-control"} %>
  <% Settings.filt.conditions.each do |key, val| %>
    <div class="filter-by">
      <%= radio_button_tag :filter_by, key,
        params[:filter_by] == key.to_s %>
      <%= label_tag "", val %>
    </div>
  <% end %>
  <%= submit_tag t("filter"), class: "form-control" %>
<% end %>

app/views/products/_info_product.html.erb
<div class="info-product container">
  <div class="col-md-7 left">
    <div class="header">
      <%= image_tag @product.image.url, class: "image-url" %>
    </div>
    <div class="bottom">
      <hr>
    </div>
  </div>
  <div class="col-md-5 right">
    <hr>
    <h1>
    <p class="glyphicon glyphicon-cutlery fa-2x text-success"></p>
      <%= @product.name %>
    </h1>
    <hr>
    <h2><%= @product.description %></h2>
    <hr>
    <h3>
      <p class="glyphicon glyphicon-usd"></p>
      <%= product_price @product.price %>
    </h3>
    <hr>
    <p class="aa-book-avilability">
      <span>
      <strong><%= t "product_rating" %>: </strong>
      </span>
    </p>
    <div class="aa-product-rating rating" id = "rating_star">
      <% i = 1 %>
      <% while i <= @product.rating.floor do %>
        <%= show_rating "star-active" %>
        <% i += 1 %>
      <% end %>
      <% while i <= 5 do %>
        <%= show_rating "" %>
        <% i += 1 %>
      <% end %>
    </div>
    <hr>
    <div>
      <%= render "rate_form", object: @product %>
    </div>
    <hr>
    <%= social_share_button_tag @product.name %>
    <hr>
    <%= link_to cart_path(@product.id), remote: true,
      method: :put, class: "btn btn_add_to_cart" do %>
      <span class="glyphicon glyphicon-shopping-cart"></span>
      <%= t "cart.add_to_card" %>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<li class="wow fadeInLeft"
  data-wow-duration="300ms" data-wow-delay="300ms">
  <div class="blog-img">
    <%= link_to "#" do %>
      <%= image_tag("blog-img-1.jpg", class: "wow fadeInUp",
        alt: "blog-img") %>
    <% end %>
  </div>
  <div class="content-right">
    <h3><%= product.name %></h3>
    <p><%= product.description %></p>
    <p><%= product.category.name %></p>
    <div class="product-rating" data-score="<%= product.rating %>"></div>
    <p><%= t "price" %><%= t "colon"%><%= number_with_precision(product.price,
      precision: 0)%> <%= t "vnd" %></p>
    <%= link_to t("btn_view"), product_path(product),
      class: "btn btn-default btn-more-info bounceIn" %>
  </div>
</li>

app/views/products/_rate.html.erb
<%= form_for current_user.active_rates.build, remote: true do |f| %>
  <div><%= hidden_field_tag :product_id, object.id %></div>
  <table class="data-table" id="product-review-table">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <% Settings.rates.each do |rate| %>
          <th><span class="nobr"><%= rate %></span></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= t "product_rate" %>: </td>
        <% Settings.rates.each do |rate| %>
        <td>
          <%= f.radio_button :rate, rate, class: "radio" %>
        </td>
        <% end %>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/products/_rate_form.html.erb
<div id=<%= "rate_form_#{object.id}" %> class = "rate_form">
  <% if current_user.rating? object %>
    <%= render "products/rerate", object: object %>
  <% else %>
    <%= render "products/rate", object: object %>
  <% end %>
</div>

app/views/products/_rerate.html.erb
<%= form_for current_user.active_rates.find_by(product_id: object.id),
  remote: true do |f| %>
  <table class="data-table" id="product-review-table">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <% Settings.rates.each do |rate| %>
          <th><span class="nobr"><%= rate %></span></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= t "product_rate" %>: </td>
        <% Settings.rates.each do |rate| %>
        <td>
          <%= f.radio_button :rate, rate, class: "radio" %>
        </td>
        <% end %>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/products/_search_form.html.erb
<%= form_tag products_path, method: :get, id: "products_search" do %>
  <%= hidden_field_tag :filter_by, params[:filter_by] %>
  <%= hidden_field_tag :category_id, params[:category_id] %>
  <div>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag t "search" %>
  </div>
<% end %>

app/views/products/index.html.erb
<% provide :title, t("product_show_list") %>
<div id="blog-products-in">
  <div class="container">
    <h1 class="heading"><%= t "blog_list" %>
      <span><%= t "blog_food" %></span><%= t "blog_and" %>
      <span><%= t "blog_drink" %></span>
    </h1>
    <div class="row">
      <div class="col-md-3">
        <%= render "users/menu" %>
      </div>
      <div class="col-md-9">
        <div class="block">
          <div class="search-and-filter">
            <div class="user-filter-word">
              <%= render "filter_form" %>
            </div>
            <div>
              <%= render "search_form" %>
            </div>
          </div>
          <ul>
            <% if @products.any? %>
              <div id="products"><%= render @products %></div>
            <% else %>
              <%= t "cant_find_result" %>
            <% end %>
          </ul>
        </div>
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= csrf_meta_tag %>
<%= render "layouts/header_index" %>
<h1 class="heading wow fadeInUp"
  data-wow-duration="400ms"
  data-wow-delay="500ms" ><%= t "about_information" %><span>
  <%= t "about_product" %></span> </br><%= t "about_website" %><span>
  <%= t "about_framgia" %></span>
</h1>
<div class="page-content">
  <div class="container">
    <div class="row cart-item-show-info">
      <%= render "info_product" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="response">
    <h3><%= t "comments" %>(<%= @comments.length %>)</h3>
  </div>
  <div id="comments-container">
    <%= paginate @comments %>
    <%= render @comments %>
  </div>
  <div class="opinion">
    <input type="hidden" value="<%= @product.id %>" id="product-id">
    <div class="form-group">
      <input type="text" name="content" id = "content" >
    </div>
    <div class="form-group">
      <button id="comment" >
        <%= t "comments" %>
      </button>
  </div>
</div>
<%= render "layouts/footer_index" %>